language: objective-c
osx_image: xcode9
script:
    - xcodebuild build test -sdk macosx -project RubyBridge.xcodeproj -scheme RubyBridge-Package CODE_SIGNING_REQUIRED=NO -enableCodeCoverage YES VALID_ARCHS=x86_64
after_success:
    - bash <(curl -s https://codecov.io/bash) -J 'RubyBridge' -X gcov -X coveragepy
