name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  macos:
    name: macOS 11 
    runs-on: macos-11.0
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.5.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Ruby
        run: |
          gem install rouge
          gem install wikipedia-client
          ruby --version
      - name: Tests
        run: swift test --enable-code-coverage
      - name: Coverage
        run: |
          xcrun llvm-cov export -format lcov .build/debug/RubyGatewayPackageTests.xctest/Contents/MacOS/RubyGatewayPackageTests -instr-profile .build/debug/codecov/default.profdata -ignore-filename-regex "(Test|checkouts)" > coverage.lcov
          bash <(curl -s https://codecov.io/bash) -f coverage.lcov

  linux:
    name: ubuntu latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Ruby
        run: |
          gem install rouge
          gem install wikipedia-client
          ruby --version
          which ruby
          ls -l /opt/hostedtoolcache/Ruby
          ls -l /opt/hostedtoolcache/Ruby/2.7.3
          ls -l /opt/hostedtoolcache/Ruby/2.7.3/x64
          ls -l /opt/hostedtoolcache/Ruby/2.7.3/x64/lib
      - name: CRuby
        run: |
          swift package update 
          swift package edit CRuby
          Packages/CRuby/cfg-cruby --mode custom --path /opt/hostedtoolcache/Ruby/2.7.3/x64
          cat Packages/CRuby/CRuby.pc
          cat Packages/CRuby/Sources/CRuby/module.modulemap
          cat Packages/CRuby/Sources/CRuby/ruby_headers.h
      - name: Tests
        run: |
          export PKG_CONFIG_PATH=$(pwd)/Packages/CRuby:$PKG_CONFIG_PATH
          export LD_LIBRARY_PATH=/opt/hostedtoolcache/Ruby/2.7.3/x64/lib:$LD_LIBRARY_PATH
          swift test
